name: Terminal Output

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: |
        echo "This is a test message."
        echo "Another message to log."
        
